"""add in players column for game_records table

Revision ID: 00cabdbd76df
Revises: eb60322676d4
Create Date: 2023-10-28 10:01:36.377295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cabdbd76df'
down_revision: Union[str, None] = 'eb60322676d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_description', table_name='items')
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_items_title', table_name='items')
    op.drop_table('items')
    op.add_column('game_records', sa.Column('players', sa.ARRAY(sa.String()), nullable=True))
    op.execute("ALTER TABLE game_records ALTER COLUMN expansion TYPE expansion_options USING expansion::expansion_options")
    op.alter_column('game_records', 'expansion',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Catan Base', 'Seafarers', 'Cities & Knights', 'Explorers & Pirates', 'Extended', 'Game of Thrones', name='expansion_options'),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('game_records', 'expansion',
               existing_type=sa.Enum('Catan Base', 'Seafarers', 'Cities & Knights', 'Explorers & Pirates', 'Extended', 'Game of Thrones', name='expansion_options'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('game_records', 'players')
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='items_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    # ### end Alembic commands ###
