"""Add in column for user pfp image url

Revision ID: 0a018e97f755
Revises: aa31f574b3e5
Create Date: 2023-12-16 16:37:58.936936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a018e97f755'
down_revision: Union[str, None] = 'aa31f574b3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pfp_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_pfp_url'), 'users', ['pfp_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pfp_url'), table_name='users')
    op.drop_column('users', 'pfp_url')
    # ### end Alembic commands ###
