"""remove unique on pfp_url for purpose of default image

Revision ID: d9fab5b78245
Revises: 0a018e97f755
Create Date: 2023-12-16 16:40:02.123896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fab5b78245'
down_revision: Union[str, None] = '0a018e97f755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_pfp_url', table_name='users')
    op.create_index(op.f('ix_users_pfp_url'), 'users', ['pfp_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pfp_url'), table_name='users')
    op.create_index('ix_users_pfp_url', 'users', ['pfp_url'], unique=False)
    # ### end Alembic commands ###
